version: '3.8'

services:
  frontend:
    image: demoworkeracr.azurecr.io/azure-openai-demo-frontend
    platform: linux/arm64
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - pg_network

  backend:
    image: demoworkeracr.azurecr.io/azure-openai-demo-backend
    platform: linux/arm64
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks:
      - pg_network
    depends_on:
      - nginx
  nginx:
    image: demoworkeracr.azurecr.io/azure-openai-demo-nginx
    platform: linux/arm64
#    volumes:
#      - /nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
